### ISSUE TITLE
Create and doc new rule CREATE_PERP_LINE_TO_LINE

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#165]
Valueinfo: CREATE_PERP_LINE_TO_LINE
Similar to the Create prep line rule, this rule looks at a feature offset from a line, finds the closest point and creates a perpendicular line.

Source: Line feature layer or feature class: Feature layer containing the existing line features.

Neighborhood	: Value: Distance around each point to search for a line feature.

Target: Line feature layer or feature class: Feature layer to contain the new perpendicular lines.

Template (Optional)	: Editing template: Editing template used to symbolize and attribute the new line feature.
<span><b>Salesforce ID:</b> BUG-000100964</span><br/>

**Comment by MikeMillerGIS** [comment]
@clareprice @ScottOppmann We will have to add a new value to the dynamic value domain

**Comment by MikeMillerGIS** [comment]
Linking to geonet issue: https://geonet.esri.com/message/650363-re-attribute-assistant-create-perpendicular-line

Bug: BUG-000100964

**Comment by guruesri** [comment]
Hi Mike,
A couple question/enhancement on the CREATE_PERP_LINE value method.
1) Can we allow user to specify the TABLENAME with TYPE field name and its value. This will allow this tool to be triggered only on a subtype/type field value from a point feature class. example - I want to trigger this only when I added endcap not all type of fitting features.

2) Can we provide an option to decide the side to draw the perpendicular line - like R-Right L-LEFT based on the digitized direction of the underline line feature? Srinivas thinks providing the option to prompt for LENGTH instead of a static value will be a good option as well.

Thanks,
Guru

**Comment by MikeMillerGIS** [comment]
@guruesri you can use subtypes to limit a rule, the table name can be feature class|subtype.  This rules also uses the selected point, finds the closest line and draws the line from the point to the line

**Comment by MikeMillerGIS** [comment]
Example 

![image](https://cloud.githubusercontent.com/assets/2707285/22948026/0c833b48-f2cb-11e6-91f5-cc5edf039f66.png)

**Comment by MikeMillerGIS** [comment]
This rule is similar to the auto add laterals

**Comment by pLeBlanc93** [comment]
new method documented

**Comment by guruesri** [comment]
@MikeMillerGIS we need to be able to specify the type on the point feature class in your example wServiceConnection, let us say we want to fire this rule only when wServiceConnection of Residential type is added.

**Comment by guruesri** [comment]
@MikeMillerGIS, sorry, i did not read your response thoroughly earlier. i now got what you said about adding featureclass|subtype name. does this mean, i need to have subtype field defined in the system or it can work on any type domain driven field?

**Comment by MikeMillerGIS** [comment]
Subtype is required

**Comment by guruesri** [comment]
Ok. thanks!
