### ISSUE TITLE
BUG-000100682  The Save Edits button in the Project Cost Estimating Window from the Capital Planning add-in doesn’t save edits made to CIP Project Details.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#166]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100682</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 11/09/2016 7:02 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100682</span><br/>
<span><b>Work Around:</b> Use the Save Selected Assets to a Project button which will create a new project that contains duplicate features for all of the original project's assets.

Then, in the CIP Project Overviews layer, delete the original project.  Because there are composite relationships that relate the overview to CIP Projects, the related Project will be deleted.  There are other composite relationships that will cascade to delete the related Project Location and assets, thus leaving the updated project.</span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
this is expected behavior, to overwrite a project, you must use the same name.

**Comment by clareprice** [comment]
@MikeMillerGIS Verified.

**Comment by shoe913** [comment]
This is working, however the tick box to rename the project feels like it is hidden. 

Instead of the tick box, would it be possible to have a verification after saving the changes?

The new workflow would be:
1) Start edit session make changes
2) Click save
3) Dialog pops up which says something like "Do you wish to over write existing or create new?". This could have a tick box to "always do selected". 
4) Edits are saved as desired.

This will help to reduce confusion as the box is not ticked off by default and users will (like I did) just miss it completely.

**Comment by MikeMillerGIS** [comment]
I think that makes sense, let me look at it

**Comment by MikeMillerGIS** [comment]
This has been changed from the check to a label and prompt on save @shoe913 @pLeBlanc93
