### ISSUE TITLE
Valve Isolation Trace and Closed Valves

### ISSUE THREAD

**Issue by timjojojo** [Esri/local-government-desktop-addins#30]
I have run into a issue where Valve Isolation trace does not take closed valves into consideration when returning the Services effected by the isolation. 

Granted this does not happen a lot, but in this particular instance the closed valve would have created a dead end and left more services out of water than what the Isolation Trace returned.

Is there a way for the tool to take closed valves into consideration?

Thanks,

Tim

**Comment by MikeMillerGIS** [comment]
Tim,
   The tool returns all valves regardless of being closed or open.  The only valves that are skipped are ones that match the operable status field value.  If you are using the open/close field for operable status, then you should change that.  You should use a different field.  This field should only be set on open valves that are not able to be closed.

**Comment by timjojojo** [comment]
I actually posted about this almost a year ago
( https://geonet.esri.com/thread/90651 ) and obviously forgot to do as you
advised and make a suggestion on github until now.

The concern is not so much the valve but the meters that would be cut off
from water but not listed in the trace.


Thanks

**Comment by MikeMillerGIS** [comment]
Tim,
   Maybe a picture will help.  I am not sure what is going on.  To be clear, are we talking about the trace model or the tool on the Water Utilities Reporting Toolbar?  The trace does stop at all valves in both.  The valve layer is considered the Disabled Layer in the trace routine.  Since the trace stops at a closed valve, customers on the newly isolated area will be returned.  

Are you asking for if you close a valve, which would result in a dead end, these customers would not be returned?  We do a version of this, each valve does a trace back to the source, and if there is no path, it is remove and not returned.  Does this actually put a barrier at each closed valve, no, so if that is what you asking for, we can add that particular scenario as an issue.


Issue:  Trace need to place barriers at each closed valve when running internal trace to identify if a valve needs to be closed and is feed by a source.

**Comment by timjojojo** [comment]
It is the Tool in the Water Utilities Reporting Toolbar.

Hopefully this little sketch will make sense.

![valveisolation](https://cloud.githubusercontent.com/assets/10552378/5766521/3af60e68-9cd0-11e4-8534-a7648d7a85f7.png)

**Comment by MikeMillerGIS** [comment]
Yes it does, thanks!  I will see what I can do.  This trace is quite complicated internally, but I think we can make this happen.

**Comment by MikeMillerGIS** [comment]
Prototype for this checked in today - https://github.com/Esri/local-government-desktop-addins/commit/4af02e5e3889923a31b343610721217fcc360ad9

**Comment by MikeMillerGIS** [comment]
New function adds all closed valves as edge barriers(junction barriers would not work with the way the trace is being used).  The edge barriers block the trace from going through a closed valve.  This will also create a more accurate representation of the outage when a downstream closed valve represents a larger outage area.  

 <add key="TraceIsolation_Valve_ClosedValveQuery" value="CURROPEN = 0" />  needs to be added to config after
 <add key="TraceIsolation_Valve_FeatureLayer" value="Water System Valves|Water Control Valves" />

**Comment by MikeMillerGIS** [comment]
help updated

**Comment by ambreenmoeen** [comment]
I think the valve layer is viewed as the Disabled Layer in the following schedule. Since the following stops at a closed valve, clients on the recently confined territory will be returned. If you close a valve, which would bring about a deadlock, these clients would not be returned? We complete a form of this, every valve completes a follow back to the source, and if there is no way, it is expelled and not returned. Does this really put a hindrance at each close [Isolation valve](https://www.clarksol.com/valves-landing-page/), no, so if that is what you requesting, we can include that specific situation as an issue?

**Comment by MikeMillerGIS** [comment]
@ambreenmoeen I am unsure if that was a real question or spam as you linked to a product page. If it is a real question, I do not understand what you are asking.

**Comment by sakarami** [comment]
Hello. I want understand the structure this tools. any one can help me?

**Comment by MikeMillerGIS** [comment]
You can find more info here:
http://solutions.arcgis.com/utilities/water/help/network-editing/
